name: node-wizard
serviceAccountName: node-wizard

replicaCount: 3

image:
  repository: ghcr.io/cnwizards/node-wizard
  tag: dev-latest
  pullPolicy: Always

resources: {}
#  limits:
#    cpu: 250m
#    memory: 512Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

# Node Wizard prometheus exporter configuration
service:
  type: ClusterIP
  port: 8989
  targetPort: 8989

# ServiceMonitor configuration
serviceMonitor:
  enabled: false
  extraLabels: {}
    # release: prom-stack

# Node Wizard configuration. These values must be set.
env:
  logLevel: "info"
  ignoreAllDaemonsets: "true"
  deleteEmptyDirData: "true"
  forceDeletePods: "true"
